version: '3.3'
services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: demo
    volumes:
      - ./db/sql/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "7080:8080"
    depends_on:
     - db